### PR TITLE
Add Mage Frost Icicles Buff charges as RUNE && Fix ColorPicker

### PR DESCRIPTION
**Pull request by huiyuanai709**
Add Mage Frost ICICLES Buff treat as RUNE

Screenshot 2024-08-21 214618

### CODE REVIEW

**Comment by huiyuanai709** [comment]
@NephMakes Hello, Review these changes please

**Comment by NephMakes** [comment]
Oh hey. I didn't get a notification for this until today. I'll take a look.

**Comment by NephMakes** [comment]
Have you tested this in-game? After switching between Frost and non-Frost specializations? It looks like it wouldn't work because you're calling GetSpecialization() at the top of Mage.lua, instead of inside a function that would return correct spec info. 

Oh wait nvm I see the next commit where you fixed it.

**Comment by NephMakes** [comment]
Ok, cool. Thanks! I'll get a release up and credit you as a contributor.

**Pull request merged**
